import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="index.css" rel="stylesheet"></link>
      </Head>

      <main className="p-4">
        {/* navbar */}
        <div className="float-left mx-8">
          <div class="grid-cols-2">
              <img src="assets/logo_sekolah.png" alt="Logo Sekolah" width="40px" height="40px" class="inline-block"/>
              <span id="nama-sekolah" class="grid-rows-2 text-sm mx-4 align-middle inline-block">
                  <p class="text-start">SMP MUHAMMADIYAH 1</p>
                  <p class="text-start">DENPASAR</p>
              </span>
          </div>
        </div>

        <div class="grid grid-cols-3">
            <div id="nav-menu" class="col-span-2 grid-cols-4 ml-16 lg:space-x-8">
                <span>Home</span>
                <span>Informasi PPDB</span>
                <span>Kontak</span>
                <span>Daftar PPDB</span>
            </div> 
            <div class="mr-4">
                <button class="float-right rounded-md grid bg-blue-900 hover:bg-blue-700 duration-700 text-white p-2 px-8 text-sm ease-in-out">Download Brosur</button>
            </div>
        </div>


      {/* <!-- login --> */}
      <div id="login" class="mt-18 bg-indigo-500 grid grid-cols-2 p-4 mx-8 rounded-lg">
      <div class="relative text-white">
            <p class="text-4xl mb-3"> Gali Potensi, </p>
            <p class="text-4xl mb-3"> Raih Prestasi </p>
            <div class="my-2 text-xl">
                <p> Satu langkah lebih dekat dengan impianmu, </p>
                <p> dengan mulai belajar di lembaga pendidikan terbaik. </p>
            </div>
                
            <div class="space-x-4 mt-10">
                <button class="bg-blue-900 hover:bg-blue-700 p-2 px-8 rounded-md">Login</button>
                <button class="bg-yellow-400 hover:bg-yellow-300 p-2 px-8 rounded-md">Cek Status Pembayaran</button>
            </div>
        </div>
        <div class="relative">
            <img class="absolute top-0 right-0" src="assets/blob-kuning.svg" alt="blob blob-kuning" width="130" height="130"></img>
            <img class="float-right z-10 relative" src="assets/pelajar.png" height="350" width="200"></img>
            <img class="absolute bottom-0 right-20" src="assets/blob-hijau.svg" alt="blob blob-hijau" width="130" height="130"></img>
        </div>
      </div>

      </main>
    </>
  )
}
